---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### Backgrounds 
* [what is m6A modification?](m6A_characteristics.html)
* [m6A-switch mechanisms]
* [m6A variation contributes to heritability of immune diseases]

### Genetic variants may act through m6A-switch to cause disease
Test the enrichment for dsRNAs formed by m6A-switch with GWAS variants 

* [identify transcripts that can form dsRNAs](check_double_strand.html)
* [visualize m6A sites and nearby double-strand RNAs](learn_gviz.html)

### Genetic variants contribute to trait through PTR mechanisms

* [running cTWAS with multiple QTLs from Geuvadis LCLs](learn_ctwas.html)
* cTWAS results - blood related traits
  - [white blood count](wbc_m6A_output_hg19.html)
  - [red blood count](rbc_m6A_output_hg19.html)
  - [lymphocyte count](lymph_m6A_output_hg19.html)
  - [granulocyte count](granulo_m6A_output_hg19.html)
  - [neutrophil count](neutroph_m6A_output_hg19.html)
  - [eosinophil count](eosinoph_m6A_output_hg19.html)
  - [platelet count](platelet_m6A_output_hg19.html)
 * cTWAS results - immune related traits
  - [IBD](IBD_m6A_output_hg19.html)
  - [asthma](asthma_m6A_output_hg19.html)
  - [Crohn's Disease](CD_m6A_output_hg19.html)
  - [lupus](lupus_m6A_output_hg19.html)
  - [RA](RA_m6A_output_hg19.html)
  - [LDL](LDL_m6A_output_hg19.html)
  
### m6A informed fine-mapping
[Are predicted m6A QTLs enriched for GWAS signals?](predicted_m6A_QTLs_enrichment_GWAS.html)

[Are predicted m6A QTLs enriched for ClinVar variants?](predicted_m6A_QTLs_enrichment_ClinVars.html)
